import { Alchemy, Network } from "alchemy-sdk";
import Layout from "@/components/Layout";
import { ethers } from "ethers";
import { abi as NFTManagerABI } from "@uniswap/v3-periphery/artifacts/contracts/NonfungiblePositionManager.sol/NonfungiblePositionManager.json";
import Head from "next/head";
import Dashboard from "@/components/Dashboard";
import { Box, Flex } from "@chakra-ui/react";

const positionAddress = "0xC36442b4a4522E871399CD717aBDD847Ab11FE88";
const address = "0xb3f95a8d2fc85fe1ac9f892912246db8631030ec";
const contract = "0xc36442b4a4522e871399cd717abdd847ab11fe88";
const alchemyApiKey = "e9qYo8yfVgVdaRPxsDqzUEpKNxENIi_8";

const config = {
  apiKey: alchemyApiKey,
  network: Network.ARB_MAINNET,
};
const alchemy = new Alchemy(config);

const provider = new ethers.providers.AlchemyProvider(
  "arbitrum",
  alchemyApiKey
);

async function getAlchemyData() {
  let liquiditys: any[] = [];
  const { ownedNfts } = await alchemy.nft.getNftsForOwner(address);

  const NFTManagerContract = new ethers.Contract(
    positionAddress,
    NFTManagerABI,
    provider
  );

  ownedNfts.map(async (token) => {
    const data = await NFTManagerContract.positions(token.tokenId);
    console.log(data);
    liquiditys.push({
      feeGrowthInside0LastX128: data.feeGrowthInside0LastX128.toString(),
      feeGrowthInside1LastX128: data.feeGrowthInside1LastX128.toString(),
      liquidity: data.liquidity.toString(),
    });
  });

  // console.log(liquiditys);
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <Flex justifyContent="center">
          <Box
            bg="#232a38"
            w="1100px"
            borderRadius={"2xl"}
            margin={"8"}
            border={"solid gray 1px"}
            padding={"4"}
          >
            <Dashboard />
          </Box>
        </Flex>
      </Layout>
    </>
  );
}

