'use client';
import './globals.css';
import useAuthStore from '@/stores/auth.store';
import { useRouter, usePathname } from 'next/navigation';
import { useEffect } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const { isLoggedIn, setIsLoggedIn, setUser } = useAuthStore();
  const { push } = useRouter();
  const path = usePathname();

  useEffect(() => {
    const user = localStorage.getItem('user');
    if (user && !isLoggedIn) {
      setUser(JSON.parse(user));
      setIsLoggedIn(true);
    }
  }, [isLoggedIn, setIsLoggedIn, setUser]);

  useEffect(() => {
    if (!isLoggedIn && path !== '/login' && !isLoggedIn && path !== '/signup') {
      push('/login');
    }
    if (isLoggedIn && path === '/login') {
      push('/');
    }
  }, [isLoggedIn, path, push]);

  return (
    <html lang="pt-br">
      <body>
        {!isLoggedIn && path !== '/login' && null}
        {!isLoggedIn && path === '/login' && children}
        {!isLoggedIn && path === '/signup' && children}
        {isLoggedIn && children}
      </body>
    </html>
  );
}
